package com.AdvancedScala.MultiThreadingDurgaSoft

object Learning12_DaemonThreads {
  def main(args: Array[String]): Unit = {

    /**
     * The threads which are executing in the background are called daemon threads.
     * Examples : Garbage Collector, Signal Dispatcher etc.,
     * The main objective of daemon threads is to provide support for non-daemon threads example main thread
     * If main thread run with low memory then JVM runs GC to destroy useless objects
     * Usually the priority of daemon threads will have low priority but based on our requirement daemon threads can run with high priority
     * We can check daemon nature of a thread by using isDaemon method of Thread class
     * We can change daemon nature of a thread by using setDaemon(boolean) method but changing daemon nature is possible before starting of a thread
     * only after starting a thread if we are trying to change daemon nature we will get RuntimeException saying IllegalThreadStateException
     * By default main thread is always non-daemon and for all remaining threads daemon nature will be inherited from Parent to Child
     * If parent thread is daemon then child thread is also daemon and if parent thread is non-daemon then child thread is also non-daemon
     * It is impossible to change daemon nature of main thread because it is already started by JVM at the beginning of the program
     * Whenever last non-daemon thread terminates automatically all daemon threads will be terminated irrespective of where they are executing
     */

    println(s"Is main thread daemon ? ${Thread.currentThread().isDaemon}")
    val t1 = new Thread(() => println("child thread"))
    println(s"Is child thread daemon ? ${t1.isDaemon}")
    t1.setDaemon(true)
    println(s"Is child thread daemon after changing ? ${t1.isDaemon}")
    t1.start()

    val t2 = new Thread(() => {
      (1 to 10).foreach { x =>
        println("thread started executing")
        Thread.sleep(500)
        println(s"The value generated by child thread is : ${x}")
      }
    })

    t2.setDaemon(true)
    t2.start()
    println("End of main method")

    /**
     * In Java multithreading is implemented by following the below two models
     *   1. Green Thread Model : The thread which is managed completely by JVM without taking underlying OS support is called green thread
     *      Very few operating systems sun solaris provide support for green thread model
     *      This model is deprecated and not recommended to use
     *   2. Native OS Model : In this model the thread which is managed by the JVM with the help of underlying OS
     *      Most of the operating systems support native OS model
     *
     * We can stop a thread execution by using stop method of thread class
     * Once we call stop the thread will enter DEAD state
     * stop method is deprecated and is not recommended to use
     *
     * We can suspend a thread suspend method of thread class then immediately the thread will enter SUSPENDED state
     * We can resume a suspended thread by using resume method of thread class then suspended thread can continue its execution
     * Both these methods are deprecated not recommended to use
     */

  }
}
